var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.6.1
 * source: vernite.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export var tutorial;
(function (tutorial) {
    var _Person_one_of_decls, _AddressBook_one_of_decls, _Author_one_of_decls, _Change_one_of_decls;
    let Kind;
    (function (Kind) {
        Kind[Kind["UPDATED"] = 0] = "UPDATED";
        Kind[Kind["DELETED"] = 1] = "DELETED";
    })(Kind = tutorial.Kind || (tutorial.Kind = {}));
    class Person extends pb_1.Message {
        constructor(data) {
            super();
            _Person_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [4], __classPrivateFieldGet(this, _Person_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("phones" in data && data.phones != undefined) {
                    this.phones = data.phones;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set name(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0);
        }
        set id(value) {
            pb_1.Message.setField(this, 2, value);
        }
        get email() {
            return pb_1.Message.getFieldWithDefault(this, 3, "");
        }
        set email(value) {
            pb_1.Message.setField(this, 3, value);
        }
        get phones() {
            return pb_1.Message.getRepeatedWrapperField(this, Person.PhoneNumber, 4);
        }
        set phones(value) {
            pb_1.Message.setRepeatedWrapperField(this, 4, value);
        }
        static fromObject(data) {
            const message = new Person({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.phones != null) {
                message.phones = data.phones.map(item => Person.PhoneNumber.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.phones != null) {
                data.phones = this.phones.map((item) => item.toObject());
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.id != 0)
                writer.writeInt32(2, this.id);
            if (this.email.length)
                writer.writeString(3, this.email);
            if (this.phones.length)
                writer.writeRepeatedMessage(4, this.phones, (item) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Person();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.id = reader.readInt32();
                        break;
                    case 3:
                        message.email = reader.readString();
                        break;
                    case 4:
                        reader.readMessage(message.phones, () => pb_1.Message.addToRepeatedWrapperField(message, 4, Person.PhoneNumber.deserialize(reader), Person.PhoneNumber));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return Person.deserialize(bytes);
        }
    }
    _Person_one_of_decls = new WeakMap();
    tutorial.Person = Person;
    (function (Person) {
        var _PhoneNumber_one_of_decls;
        let PhoneType;
        (function (PhoneType) {
            PhoneType[PhoneType["MOBILE"] = 0] = "MOBILE";
            PhoneType[PhoneType["HOME"] = 1] = "HOME";
            PhoneType[PhoneType["WORK"] = 2] = "WORK";
        })(PhoneType = Person.PhoneType || (Person.PhoneType = {}));
        class PhoneNumber extends pb_1.Message {
            constructor(data) {
                super();
                _PhoneNumber_one_of_decls.set(this, []);
                pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _PhoneNumber_one_of_decls, "f"));
                if (!Array.isArray(data) && typeof data == "object") {
                    if ("number" in data && data.number != undefined) {
                        this.number = data.number;
                    }
                    if ("type" in data && data.type != undefined) {
                        this.type = data.type;
                    }
                }
            }
            get number() {
                return pb_1.Message.getFieldWithDefault(this, 1, "");
            }
            set number(value) {
                pb_1.Message.setField(this, 1, value);
            }
            get type() {
                return pb_1.Message.getFieldWithDefault(this, 2, Person.PhoneType.MOBILE);
            }
            set type(value) {
                pb_1.Message.setField(this, 2, value);
            }
            static fromObject(data) {
                const message = new PhoneNumber({});
                if (data.number != null) {
                    message.number = data.number;
                }
                if (data.type != null) {
                    message.type = data.type;
                }
                return message;
            }
            toObject() {
                const data = {};
                if (this.number != null) {
                    data.number = this.number;
                }
                if (this.type != null) {
                    data.type = this.type;
                }
                return data;
            }
            serialize(w) {
                const writer = w || new pb_1.BinaryWriter();
                if (this.number.length)
                    writer.writeString(1, this.number);
                if (this.type != Person.PhoneType.MOBILE)
                    writer.writeEnum(2, this.type);
                if (!w)
                    return writer.getResultBuffer();
            }
            static deserialize(bytes) {
                const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new PhoneNumber();
                while (reader.nextField()) {
                    if (reader.isEndGroup())
                        break;
                    switch (reader.getFieldNumber()) {
                        case 1:
                            message.number = reader.readString();
                            break;
                        case 2:
                            message.type = reader.readEnum();
                            break;
                        default: reader.skipField();
                    }
                }
                return message;
            }
            serializeBinary() {
                return this.serialize();
            }
            static deserializeBinary(bytes) {
                return PhoneNumber.deserialize(bytes);
            }
        }
        _PhoneNumber_one_of_decls = new WeakMap();
        Person.PhoneNumber = PhoneNumber;
    })(Person = tutorial.Person || (tutorial.Person = {}));
    class AddressBook extends pb_1.Message {
        constructor(data) {
            super();
            _AddressBook_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [1], __classPrivateFieldGet(this, _AddressBook_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("people" in data && data.people != undefined) {
                    this.people = data.people;
                }
            }
        }
        get people() {
            return pb_1.Message.getRepeatedWrapperField(this, Person, 1);
        }
        set people(value) {
            pb_1.Message.setRepeatedWrapperField(this, 1, value);
        }
        static fromObject(data) {
            const message = new AddressBook({});
            if (data.people != null) {
                message.people = data.people.map(item => Person.fromObject(item));
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.people != null) {
                data.people = this.people.map((item) => item.toObject());
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.people.length)
                writer.writeRepeatedMessage(1, this.people, (item) => item.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new AddressBook();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        reader.readMessage(message.people, () => pb_1.Message.addToRepeatedWrapperField(message, 1, Person.deserialize(reader), Person));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return AddressBook.deserialize(bytes);
        }
    }
    _AddressBook_one_of_decls = new WeakMap();
    tutorial.AddressBook = AddressBook;
    class Author extends pb_1.Message {
        constructor(data) {
            super();
            _Author_one_of_decls.set(this, []);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _Author_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("role" in data && data.role != undefined) {
                    this.role = data.role;
                }
            }
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 1, "");
        }
        set name(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get role() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set role(value) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data) {
            const message = new Author({});
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.role != null) {
                message.role = data.role;
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.role != null) {
                data.role = this.role;
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.name.length)
                writer.writeString(1, this.name);
            if (this.role.length)
                writer.writeString(2, this.role);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Author();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.name = reader.readString();
                        break;
                    case 2:
                        message.role = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return Author.deserialize(bytes);
        }
    }
    _Author_one_of_decls = new WeakMap();
    tutorial.Author = Author;
    class Change extends pb_1.Message {
        constructor(data) {
            super();
            _Change_one_of_decls.set(this, [[4, 5]]);
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3], __classPrivateFieldGet(this, _Change_one_of_decls, "f"));
            if (!Array.isArray(data) && typeof data == "object") {
                if ("kind" in data && data.kind != undefined) {
                    this.kind = data.kind;
                }
                if ("patch" in data && data.patch != undefined) {
                    this.patch = data.patch;
                }
                if ("tags" in data && data.tags != undefined) {
                    this.tags = data.tags;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("author" in data && data.author != undefined) {
                    this.author = data.author;
                }
            }
        }
        get kind() {
            return pb_1.Message.getFieldWithDefault(this, 1, Kind.UPDATED);
        }
        set kind(value) {
            pb_1.Message.setField(this, 1, value);
        }
        get patch() {
            return pb_1.Message.getFieldWithDefault(this, 2, "");
        }
        set patch(value) {
            pb_1.Message.setField(this, 2, value);
        }
        get tags() {
            return pb_1.Message.getFieldWithDefault(this, 3, []);
        }
        set tags(value) {
            pb_1.Message.setField(this, 3, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 4, "");
        }
        set name(value) {
            pb_1.Message.setOneofField(this, 4, __classPrivateFieldGet(this, _Change_one_of_decls, "f")[0], value);
        }
        get has_name() {
            return pb_1.Message.getField(this, 4) != null;
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 5, "");
        }
        set id(value) {
            pb_1.Message.setOneofField(this, 5, __classPrivateFieldGet(this, _Change_one_of_decls, "f")[0], value);
        }
        get has_id() {
            return pb_1.Message.getField(this, 5) != null;
        }
        get author() {
            return pb_1.Message.getWrapperField(this, Author, 6);
        }
        set author(value) {
            pb_1.Message.setWrapperField(this, 6, value);
        }
        get has_author() {
            return pb_1.Message.getField(this, 6) != null;
        }
        get name_or_id() {
            const cases = {
                0: "none",
                4: "name",
                5: "id"
            };
            return cases[pb_1.Message.computeOneofCase(this, [4, 5])];
        }
        static fromObject(data) {
            const message = new Change({});
            if (data.kind != null) {
                message.kind = data.kind;
            }
            if (data.patch != null) {
                message.patch = data.patch;
            }
            if (data.tags != null) {
                message.tags = data.tags;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.author != null) {
                message.author = Author.fromObject(data.author);
            }
            return message;
        }
        toObject() {
            const data = {};
            if (this.kind != null) {
                data.kind = this.kind;
            }
            if (this.patch != null) {
                data.patch = this.patch;
            }
            if (this.tags != null) {
                data.tags = this.tags;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.author != null) {
                data.author = this.author.toObject();
            }
            return data;
        }
        serialize(w) {
            const writer = w || new pb_1.BinaryWriter();
            if (this.kind != Kind.UPDATED)
                writer.writeEnum(1, this.kind);
            if (this.patch.length)
                writer.writeString(2, this.patch);
            if (this.tags.length)
                writer.writeRepeatedString(3, this.tags);
            if (this.has_name)
                writer.writeString(4, this.name);
            if (this.has_id)
                writer.writeString(5, this.id);
            if (this.has_author)
                writer.writeMessage(6, this.author, () => this.author.serialize(writer));
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes) {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Change();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.kind = reader.readEnum();
                        break;
                    case 2:
                        message.patch = reader.readString();
                        break;
                    case 3:
                        pb_1.Message.addToRepeatedField(message, 3, reader.readString());
                        break;
                    case 4:
                        message.name = reader.readString();
                        break;
                    case 5:
                        message.id = reader.readString();
                        break;
                    case 6:
                        reader.readMessage(message.author, () => message.author = Author.deserialize(reader));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary() {
            return this.serialize();
        }
        static deserializeBinary(bytes) {
            return Change.deserialize(bytes);
        }
    }
    _Change_one_of_decls = new WeakMap();
    tutorial.Change = Change;
})(tutorial || (tutorial = {}));
