var __classPrivateFieldGet = (this && this.__classPrivateFieldGet) || function (receiver, state, kind, f) {
    if (kind === "a" && !f) throw new TypeError("Private accessor was defined without a getter");
    if (typeof state === "function" ? receiver !== state || !f : !state.has(receiver)) throw new TypeError("Cannot read private member from an object whose class did not declare it");
    return kind === "m" ? f : kind === "a" ? f.call(receiver) : f ? f.value : state.get(receiver);
};
var _NewTaskNotification_one_of_decls;
/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.20.3
 * source: messages/message.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class NewTaskNotification extends pb_1.Message {
    constructor(data) {
        super();
        _NewTaskNotification_one_of_decls.set(this, []);
        pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], __classPrivateFieldGet(this, _NewTaskNotification_one_of_decls, "f"));
        if (!Array.isArray(data) && typeof data == "object") {
            if ("test" in data && data.test != undefined) {
                this.test = data.test;
            }
        }
    }
    get test() {
        return pb_1.Message.getFieldWithDefault(this, 1, "");
    }
    set test(value) {
        pb_1.Message.setField(this, 1, value);
    }
    static fromObject(data) {
        const message = new NewTaskNotification({});
        if (data.test != null) {
            message.test = data.test;
        }
        return message;
    }
    toObject() {
        const data = {};
        if (this.test != null) {
            data.test = this.test;
        }
        return data;
    }
    serialize(w) {
        const writer = w || new pb_1.BinaryWriter();
        if (this.test.length)
            writer.writeString(1, this.test);
        if (!w)
            return writer.getResultBuffer();
    }
    static deserialize(bytes) {
        const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new NewTaskNotification();
        while (reader.nextField()) {
            if (reader.isEndGroup())
                break;
            switch (reader.getFieldNumber()) {
                case 1:
                    message.test = reader.readString();
                    break;
                default: reader.skipField();
            }
        }
        return message;
    }
    serializeBinary() {
        return this.serialize();
    }
    static deserializeBinary(bytes) {
        return NewTaskNotification.deserialize(bytes);
    }
}
_NewTaskNotification_one_of_decls = new WeakMap();
